# Generated by Django 5.0.2 on 2024-04-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_img', models.FileField(default=None, max_length=250, null=True, upload_to='service/')),
                ('service_img1', models.FileField(default=None, max_length=250, null=True, upload_to='service/')),
                ('service_img2', models.FileField(default=None, max_length=250, null=True, upload_to='service/')),
                ('service_img3', models.FileField(default=None, max_length=250, null=True, upload_to='service/')),
                ('service_type', models.TextField(max_length=15)),
                # ('service_avail', models.CharField(max_length=15)),
                ('service_des', models.TextField(max_length=50)),
            ],
        ),
    ]
